export const sportTypeDisplay: Record<WhoopSportType, string> = {
	[WhoopSportType.Activity]: 'Activity',
	[WhoopSportType.Running]: 'Running',
	[WhoopSportType.Cycling]: 'Cycling',
	[WhoopSportType.Baseball]: 'Baseball',
	[WhoopSportType.Basketball]: 'Basketball',
	[WhoopSportType.Rowing]: 'Rowing',
	[WhoopSportType.Fencing]: 'Fencing',
	[WhoopSportType.FieldHockey]: 'Field Hockey',
	[WhoopSportType.Football]: 'Football',
	[WhoopSportType.Golf]: 'Golf',
	[WhoopSportType.IceHockey]: 'Ice Hockey',
	[WhoopSportType.Lacrosse]: 'Lacrosse',
	[WhoopSportType.Rugby]: 'Rugby',
	[WhoopSportType.Sailing]: 'Sailing',
	[WhoopSportType.Skiing]: 'Skiing',
	[WhoopSportType.Soccer]: 'Soccer',
	[WhoopSportType.Softball]: 'Softball',
	[WhoopSportType.Squash]: 'Squash',
	[WhoopSportType.Swimming]: 'Swimming',
	[WhoopSportType.Tennis]: 'Tennis',
	[WhoopSportType.TrackAndField]: 'Track & Field',
	[WhoopSportType.Volleyball]: 'Volleyball',
	[WhoopSportType.WaterPolo]: 'Water Polo',
	[WhoopSportType.Wrestling]: 'Wrestling',
	[WhoopSportType.Boxing]: 'Boxing',
	[WhoopSportType.Dance]: 'Dance',
	[WhoopSportType.Pilates]: 'Pilates',
	[WhoopSportType.Yoga]: 'Yoga',
	[WhoopSportType.Weightlifting]: 'Weightlifting',
	[WhoopSportType.CrossCountrySkiing]: 'Cross Country Skiing',
	[WhoopSportType.FunctionalFitness]: 'Functional Fitness',
	[WhoopSportType.Duathlon]: 'Duathlon',
	[WhoopSportType.Gymnastics]: 'Gymnastics',
	[WhoopSportType.HikingRucking]: 'Hiking/Rucking',
	[WhoopSportType.HorsebackRiding]: 'Horseback Riding',
	[WhoopSportType.Kayaking]: 'Kayaking',
	[WhoopSportType.MartialArts]: 'Martial Arts',
	[WhoopSportType.MountainBiking]: 'Mountain Biking',
	[WhoopSportType.Powerlifting]: 'Powerlifting',
	[WhoopSportType.RockClimbing]: 'Rock Climbing',
	[WhoopSportType.Paddleboarding]: 'Paddleboarding',
	[WhoopSportType.Triathlon]: 'Triathlon',
	[WhoopSportType.Walking]: 'Walking',
	[WhoopSportType.Surfing]: 'Surfing',
	[WhoopSportType.Elliptical]: 'Elliptical',
	[WhoopSportType.Stairmaster]: 'Stairmaster',
	[WhoopSportType.Meditation]: 'Meditation',
	[WhoopSportType.Other]: 'Other',
	[WhoopSportType.Diving]: 'Diving',
	[WhoopSportType.OperationsTactical]: 'Operations - Tactical',
	[WhoopSportType.OperationsMedical]: 'Operations - Medical',
	[WhoopSportType.OperationsFlying]: 'Operations - Flying',
	[WhoopSportType.OperationsWater]: 'Operations - Water',
	[WhoopSportType.Ultimate]: 'Ultimate',
	[WhoopSportType.Climber]: 'Climber',
	[WhoopSportType.JumpingRope]: 'Jumping Rope',
	[WhoopSportType.AustralianFootball]: 'Australian Football',
	[WhoopSportType.Skateboarding]: 'Skateboarding',
	[WhoopSportType.Coaching]: 'Coaching',
	[WhoopSportType.IceBath]: 'Ice Bath',
	[WhoopSportType.Commuting]: 'Commuting',
	[WhoopSportType.Gaming]: 'Gaming',
	[WhoopSportType.Snowboarding]: 'Snowboarding',
	[WhoopSportType.Motocross]: 'Motocross',
	[WhoopSportType.Caddying]: 'Caddying',
	[WhoopSportType.ObstacleCourseRacing]: 'Obstacle Course Racing',
	[WhoopSportType.MotorRacing]: 'Motor Racing',
	[WhoopSportType.HIIT]: 'HIIT',
	[WhoopSportType.Spin]: 'Spin',
	[WhoopSportType.JiuJitsu]: 'Jiu Jitsu',
	[WhoopSportType.ManualLabor]: 'Manual Labor',
	[WhoopSportType.Cricket]: 'Cricket',
	[WhoopSportType.Pickleball]: 'Pickleball',
	[WhoopSportType.InlineSkating]: 'Inline Skating',
	[WhoopSportType.BoxFitness]: 'Box Fitness',
	[WhoopSportType.Spikeball]: 'Spikeball',
	[WhoopSportType.WheelchairPushing]: 'Wheelchair Pushing',
	[WhoopSportType.PaddleTennis]: 'Paddle Tennis',
	[WhoopSportType.Barre]: 'Barre',
	[WhoopSportType.StagePerformance]: 'Stage Performance',
	[WhoopSportType.HighStressWork]: 'High Stress Work',
	[WhoopSportType.Parkour]: 'Parkour',
	[WhoopSportType.GaelicFootball]: 'Gaelic Football',
	[WhoopSportType.HurlingCamogie]: 'Hurling/Camogie',
	[WhoopSportType.CircusArts]: 'Circus Arts',
	[WhoopSportType.MassageTherapy]: 'Massage Therapy',
	[WhoopSportType.StrengthTrainer]: 'Strength Trainer',
	[WhoopSportType.WatchingSports]: 'Watching Sports',
	[WhoopSportType.AssaultBike]: 'Assault Bike',
	[WhoopSportType.Kickboxing]: 'Kickboxing',
	[WhoopSportType.Stretching]: 'Stretching',
	[WhoopSportType.TableTennis]: 'Table Tennis',
	[WhoopSportType.Badminton]: 'Badminton',
	[WhoopSportType.Netball]: 'Netball',
	[WhoopSportType.Sauna]: 'Sauna',
	[WhoopSportType.DiscGolf]: 'Disc Golf',
	[WhoopSportType.YardWork]: 'Yard Work',
	[WhoopSportType.AirCompression]: 'Air Compression',
	[WhoopSportType.PercussiveMassage]: 'Percussive Massage',
	[WhoopSportType.Paintball]: 'Paintball',
	[WhoopSportType.IceSkating]: 'Ice Skating',
	[WhoopSportType.Handball]: 'Handball',
	[WhoopSportType.F45Training]: 'F45 Training',
	[WhoopSportType.Padel]: 'Padel',
	[WhoopSportType.Barrys]: 'Barry\'s',
	[WhoopSportType.DedicatedParenting]: 'Dedicated Parenting',
	[WhoopSportType.StrollerWalking]: 'Stroller Walking',
	[WhoopSportType.StrollerJogging]: 'Stroller Jogging',
	[WhoopSportType.Toddlerwearing]: 'Toddler Wearing',
	[WhoopSportType.Babywearing]: 'Baby Wearing',
	[WhoopSportType.Barre3]: 'Barre3',
	[WhoopSportType.HotYoga]: 'Hot Yoga',
	[WhoopSportType.StadiumSteps]: 'Stadium Steps',
	[WhoopSportType.Polo]: 'Polo',
	[WhoopSportType.MusicalPerformance]: 'Musical Performance',
	[WhoopSportType.KiteBoarding]: 'Kite Boarding',
	[WhoopSportType.DogWalking]: 'Dog Walking',
	[WhoopSportType.WaterSkiing]: 'Water Skiing',
	[WhoopSportType.Wakeboarding]: 'Wakeboarding',
	[WhoopSportType.Cooking]: 'Cooking',
	[WhoopSportType.Cleaning]: 'Cleaning',
	[WhoopSportType.PublicSpeaking]: 'Public Speaking'
}

/**
 * Get the human-readable display name for a sport type
 * @param sportType - The WhoopSportType enum value
 * @returns The human-readable display name
 */
export const getSportTypeDisplay = (sportType: WhoopSportType): string => {
	return sportTypeDisplay[sportType] || 'Unknown Sport'
}